apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer-org0
  namespace: hlf
  labels:
    app: orderer-org0
spec:
  selector:
    matchLabels:
      app: orderer-org0
  template:
    metadata:
      labels:
        app: orderer-org0
    spec:
      containers:
        - name: orderer-org0
          image: hyperledger/fabric-orderer:2.4
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/hyperledger/production/orderer
              name: orderer-persistent-mount
            - mountPath: /tmp/hyperledger/shared
              name: shared-volume
            - mountPath: /tmp/hyperledger/orderer/org0
              name: orderer-mount
          env:
            - name: ORDERER_HOME
              value: "/tmp/hyperledger/orderer"
            - name: ORDERER_HOST
              value: "orderer-org0"
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: "file"
            - name: ORDERER_GENERAL_GENESISFILE
              value: "/tmp/hyperledger/shared/channel/genesis.block"
            - name: ORDERER_GENERAL_LOCALMSPID
              value: "ordererOrg0MSP"
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: "/tmp/hyperledger/orderer/org0/msp"
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: "/tmp/hyperledger/orderer/org0/tls-msp/signcerts/cert.pem"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: "/tmp/hyperledger/orderer/org0/tls-msp/keystore/key.pem"
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/tmp/hyperledger/orderer/org0/tls-msp/tlscacerts/tls-tls-ca-hlf-7052.pem]"
            - name: ORDERER_GENERAL_LOGLEVEL
              value: "debug"
            - name: FABRIC_LOGGING_SPEC
              value: "DEBUG"
            - name: ORDERER_DEBUG_BROADCASTTRACEDIR
              value: "data/logs"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: "/tmp/hyperledger/orderer/org0/tls-msp/keystore/key.pem"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: "/tmp/hyperledger/orderer/org0/tls-msp/signcerts/cert.pem"
      initContainers:
        - name: fabric-ca
          image: hyperledger/fabric-ca:1.5
          imagePullPolicy: IfNotPresent
          command: ["bash", "./tmp/hyperledger/scripts/startNetwork/enrollJobs/enrollOrdererOrg0.sh"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/shared
              name: shared-volume
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/hyperledger/orderer/org0
              name: orderer-mount
            - mountPath: /tmp/secrets/tls-ca
              name: tls-ca-cert
              readOnly: true
            - mountPath: /tmp/secrets/rca-orderer-org0
              name: rca-org0-cert
              readOnly: true
          env:
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
            - name: ORDERER_TLS_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.orderer-org0
                  key: username
            - name: ORDERER_TLS_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.orderer-org0
                  key: password
            - name: ORDERER_ORG0_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.orderer-org0
                  key: username
            - name: ORDERER_ORG0_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.orderer-org0
                  key: password
            - name: ADMIN_ORDERER_ORG0_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.admin-orderer-org0
                  key: username
            - name: ADMIN_ORDERER_ORG0_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.admin-orderer-org0
                  key: password
        - name: fabric-tools
          image: hyperledger/fabric-tools:2.4
          imagePullPolicy: IfNotPresent
          command: ["bash", "/tmp/hyperledger/scripts/startNetwork/createGenesisBlock.sh"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/shared
              name: shared-volume
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/configmaps
              name: configtx
              readOnly: true
            - mountPath: /tmp/secrets/tls-ca
              name: tls-ca-cert
              readOnly: true
            - mountPath: /tmp/secrets/rca-orderer-org0
              name: rca-orderer-org0-cert
              readOnly: true
            - mountPath: /tmp/secrets/rca-hospital1
              name: rca-hospital1-cert
              readOnly: true
            - mountPath: /tmp/secrets/rca-hospital2
              name: rca-hospital2-cert
              readOnly: true
      volumes:
        - name: orderer-persistent-mount
          persistentVolumeClaim:
            claimName: orderer-org0-pvc
        - name: orderer-mount
          persistentVolumeClaim:
            claimName: orderer-org0-shared-pvc
        - name: shared-volume
          hostPath:
            path: /mnt/hyperledger/shared
        - name: scripts
          hostPath:
            path: /mnt/hyperledger/scripts
        - name: configtx
          configMap:
            name: configtx
        - name: tls-ca-cert
          secret:
            secretName: cert.tls-ca
        - name: rca-org0-cert
          secret:
            secretName: cert.rca-org0
        - name: rca-hospital-cert
          secret:
            secretName: cert.rca-hospital1
        - name: rca-hospital2-cert
          secret:
            secretName: cert.rca-hospital2
---
apiVersion: v1
kind: Service
metadata:
  name: orderer-org0
  namespace: hlf
  labels:
    app: orderer-org0
spec:
  type: NodePort
  selector:
    app: orderer-org0
  ports:
    - name: grpcs
      protocol: TCP
      port: 7050
      nodePort: 30010
