kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: hlf
  name: rca-orderer-org0-pv
  labels:
    app: rca-orderer-org0
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/hyperledger/storage/rca-orderer-org0"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hlf
  name: rca-orderer-org0-pvc
  labels:
    app: rca-orderer-org0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
