apiVersion: apps/v1
kind: Deployment
metadata:
  name: rca-orderer-org0
  namespace: hlf
  labels:
    app: rca-orderer-org0
spec:
  selector:
    matchLabels:
      app: rca-orderer-org0
  template:
    metadata:
      labels:
        app: rca-orderer-org0
    spec:
      containers:
        - name: rca-orderer-org0
          image: hyperledger/fabric-ca:1.5
          imagePullPolicy: IfNotPresent
          command: ["fabric-ca-server", "start", "-b", "$(BOOTSTRAP_USER):$(BOOTSTRAP_PASSWORD)", "--port", "7052"]
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "/tmp/hyperledger/scripts/startNetwork/registerUsers/registerOrdererOrgUsers.sh"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/fabric-ca/crypto
              name: rca-orderer-org0-persistent-mount
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/secrets/tls-ca
              name: tls-ca-cert
              readOnly: true
            - mountPath: /tmp/secrets/cert.pem
              name: cert
              subPath: cert.pem
              readOnly: true
            - mountPath: /tmp/secrets/key.pem
              name: key
              subPath: key.pem
              readOnly: true
          env:
            - name: FABRIC_CA_HOME
              value: "/tmp/hyperledger/fabric-ca/crypto"
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_CSR_CN
              value: "rca-orderer-org0"
            - name: FABRIC_CA_SERVER_CSR_HOSTS
              value: "172.17.0.2,172.17.0.3,0.0.0.0,rca-orderer-org0.hlf,uc4.cs.uni-paderborn.de"
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: "/tmp/secrets/cert.pem"
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: "/tmp/secrets/key.pem"
            - name: BOOTSTRAP_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.rca-orderer-org0
                  key: username
            - name: BOOTSTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.rca-orderer-org0
                  key: password
            - name: ORDERER_ORG0_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.orderer-org0
                  key: username
            - name: ORDERER_ORG0_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.orderer-org0
                  key: password
            - name: ADMIN_ORDERER_ORG0_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.admin-orderer-org0
                  key: username
            - name: ADMIN_ORDERER_ORG0_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.admin-orderer-org0
                  key: password
      volumes:
        - name: rca-orderer-org0-persistent-mount 
          persistentVolumeClaim:
            claimName: rca-orderer-org0-pvc
        - name: scripts
          hostPath:
            path: /mnt/hyperledger/scripts
        - name: tls-ca-cert
          secret:
            secretName: cert.tls-ca
        - name: cert
          secret:
            secretName: cert.rca-orderer-org0
        - name: key
          secret:
            secretName: key.rca-orderer-org0

---
apiVersion: v1
kind: Service
metadata:
  name: rca-orderer-org0
  namespace: hlf
  labels:
    app: rca-orderer-org0
spec:
  type: NodePort
  selector:
    app: rca-orderer-org0
  ports:
    - name: https
      protocol: TCP
      nodePort: 30906
      port: 7052
