kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: hlf
  name: peer0-hospital2-pv
  labels:
    app: peer0-hospital2
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/hyperledger/storage/peer0-hospital2"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hlf
  name: peer0-hospital2-pvc
  labels:
    app: peer0-hospital2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
      

---


kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: hlf
  name: peer0-hospital2-couchdb-pv
  labels:
    app: peer0-hospital2
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/hyperledger/storage/peer0-hospital2-couchdb"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hlf
  name: peer0-hospital2-couchdb-pvc
  labels:
    app: peer0-hospital2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi


---


kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: hlf
  name: peer0-hospital2-dind-pv
  labels:
    app: peer0-hospital2
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/hyperledger/storage/peer0-hospital2-dind"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hlf
  name: peer0-hospital2-dind-pvc
  labels:
    app: peer0-hospital2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
