kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: hlf
  name: rca-hospital2-pv
  labels:
    app: rca-hospital2
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/hyperledger/storage/rca-hospital2"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hlf
  name: rca-hospital2-pvc
  labels:
    app: rca-hospital2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
