apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0-hospital1
  namespace: hlf
  labels:
    app: peer0-hospital1
spec:
  selector:
    matchLabels:
      app: peer0-hospital1
  template:
    metadata:
      labels:
        app: peer0-hospital1
    spec:
      containers:
        - name: peer0-hospital1
          image: hyperledger/fabric-peer:2.4
          volumeMounts:
            - mountPath: /tmp/hyperledger/hospital1/peer0
              name: peer0-hospital1-mount
            - mountPath: /var/hyperledger/production
              name: peer-persistent-mount
          env:
            - name: CORE_PEER_ID
              value: "peer0-hospital1"
            - name: CORE_PEER_LISTENADDRESS
              value: "0.0.0.0:7051"
            - name: CORE_PEER_ADDRESS
              value: "peer0-hospital1:7051"
            - name: CORE_PEER_LOCALMSPID
              value: "hospital1MSP"
            - name: CORE_PEER_MSPCONFIGPATH
              value: "/tmp/hyperledger/hospital1/peer0/msp"
            - name: CORE_VM_ENDPOINT
              value: "tcp://localhost:2375"
            - name: FABRIC_LOGGING_SPEC
              value: "debug:gossip,msp=info"
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: "/tmp/hyperledger/hospital1/peer0/tls-msp/signcerts/cert.pem"
            - name: CORE_PEER_TLS_KEY_FILE
              value: "/tmp/hyperledger/hospital1/peer0/tls-msp/keystore/key.pem"
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: "/tmp/hyperledger/hospital1/peer0/tls-msp/tlscacerts/tls-tls-ca-hlf-7052.pem"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: "peer0-hospital1:7051"
            - name: CORE_PEER_BOOTSTRAP
              value: "peer0-hospital1:7051"
            - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
              value: "true"
            - name: CORE_PEER_CHAINCODEADDRESS
              value: "peer0-hospital1:7052"
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: "0.0.0.0:7052"
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: "localhost:5984"
        - name: couchdb
          image: hyperledger/fabric-couchdb:latest
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: couchdb-persistent-mount
        - name: dind
          image: "docker:18.05.0-dind"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/docker
              name: dind-persistent-mount
      initContainers:
        - name: fabric-ca
          image: hyperledger/fabric-ca:1.5
          imagePullPolicy: IfNotPresent
          command: ["bash", "./tmp/hyperledger/scripts/startNetwork/enrollJobs/enrollPeer.sh"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/hyperledger/shared
              name: shared-volume
            - mountPath: /tmp/hyperledger/hospital1/peer0
              name: peer0-hospital1-mount
            - mountPath: /tmp/secrets/tls-ca
              name: tls-ca-cert
              readOnly: true
            - mountPath: /tmp/secrets/rca-hospital1
              name: rca-hospital1-cert
              readOnly: true
          env:
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
            - name: PEER_NUM
              value: "1"
            - name: ORG_NUM
              value: "1"
            - name: ORG_CA_PORT
              value: "7052"
            - name: PEER_TLS_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.peer0-hospital1
                  key: username
            - name: PEER_TLS_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.tls.peer0-hospital1
                  key: password
            - name: PEER_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.peer0-hospital1
                  key: username
            - name: PEER_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.peer0-hospital1
                  key: password
            
      volumes:
        - name: peer-persistent-mount
          persistentVolumeClaim:
              claimName: peer0-hospital1-pvc
        - name: couchdb-persistent-mount
          persistentVolumeClaim:
              claimName: peer0-hospital1-couchdb-pvc
        - name: dind-persistent-mount
          persistentVolumeClaim:
              claimName: peer0-hospital1-dind-pvc
        - name: scripts
          hostPath:
            path: /mnt/hyperledger/scripts
        - name: shared-volume
          hostPath:
            path: /mnt/hyperledger/shared
        - name: peer0-hospital1-mount
          emptyDir: {}
        - name: tls-ca-cert
          secret:
            secretName: cert.tls-ca
        - name: rca-hospital1-cert
          secret:
            secretName: cert.rca-hospital1
---
apiVersion: v1
kind: Service
metadata:
  name: peer0-hospital1
  namespace: hlf
  labels:
    app: peer0-hospital1
spec:
  type: NodePort
  selector:
    app: peer0-hospital1
  ports:
    - name: core
      protocol: TCP
      port: 7051
      nodePort: 30111
    - name: chaincode
      protocol: TCP
      port: 7052
