apiVersion: apps/v1
kind: Deployment
metadata:
  name: rca-hospital1
  namespace: hlf
  labels:
    app: rca-hospital1
spec:
  selector:
    matchLabels:
      app: rca-hospital1
  template:
    metadata:
      labels:
        app: rca-hospital1
    spec:
      containers:
        - name: rca-hospital1
          image: hyperledger/fabric-ca:1.5
          imagePullPolicy: IfNotPresent
          command: ["fabric-ca-server", "start", "-b", "$(BOOTSTRAP_USER):$(BOOTSTRAP_PASSWORD)", "--port", "7052"]
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "/tmp/hyperledger/scripts/startNetwork/registerUsers/registerHospital1CaUsers.sh"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/fabric-ca/crypto
              name: rca-hospital1-persistent-mount
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/secrets/cert.pem
              name: cert
              subPath: cert.pem
              readOnly: true
            - mountPath: /tmp/secrets/key.pem
              name: key
              subPath: key.pem
              readOnly: true
          env:
            - name: FABRIC_CA_HOME
              value: "/tmp/hyperledger/fabric-ca/crypto"
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_CSR_CN
              value: "rca-hospital1"
            - name: FABRIC_CA_SERVER_CSR_HOSTS
              value: "172.17.0.2,172.17.0.3,0.0.0.0,rca-hospital1.hlf,uc4.cs.uni-paderborn.de"
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: "/tmp/secrets/cert.pem"
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: "/tmp/secrets/key.pem"
            - name: BOOTSTRAP_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.rca-hospital1
                  key: username
            - name: BOOTSTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.rca-hospital1
                  key: password
            - name: PEER0_HOSPITAL1_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.peer0-hospital1
                  key: username
            - name: PEER0_HOSPITAL1_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.peer0-hospital1
                  key: password
            # - name: PEER2_ORG1_IDENTITY_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: credentials.peer2-org1
            #       key: username
            # - name: PEER2_ORG1_IDENTITY_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: credentials.peer2-org1
            #       key: password
            - name: ADMIN_HOSPITAL1_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.admin-hospital1
                  key: username
            - name: ADMIN_HOSPITAL1_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.admin-hospital1
                  key: password
            - name: SCALA_ADMIN_HOSPITAL1_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.scala-admin-hospital1
                  key: username
            - name: SCALA_ADMIN_HOSPITAL1_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.scala-admin-hospital1
                  key: password
            - name: SCALA_REGISTRATION_ADMIN_HOSPITAL1_IDENTITY_USER
              valueFrom:
                secretKeyRef:
                  name: credentials.scala-registration-admin-hospital1
                  key: username
            - name: SCALA_REGISTRATION_ADMIN_HOSPITAL1_IDENTITY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.scala-registration-admin-hospital1
                  key: password
      volumes:
        - name: rca-hospital1-persistent-mount 
          persistentVolumeClaim:
            claimName: rca-hospital1-pvc
        - name: scripts
          hostPath:
            path: /mnt/hyperledger/scripts
        - name: cert
          secret:
            secretName: cert.rca-hospital1
        - name: key
          secret:
            secretName: key.rca-hospital1
---
apiVersion: v1
kind: Service
metadata:
  name: rca-hospital1
  namespace: hlf
  labels:
    app: rca-hospital1
spec:
  type: NodePort
  selector:
    app: rca-hospital1
  ports:
    - name: https
      protocol: TCP
      nodePort: 30907
      port: 7052
