kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: worker
    extraMounts:
      - hostPath: /data/development/hyperledger
        containerPath: /mnt/hyperledger
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ehr-consortium/kind-worker"
  - role: control-plane
    extraMounts:
      - hostPath: /data/development/hyperledger
        containerPath: /mnt/hyperledger
